# Generated by Django 4.0 on 2021-12-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('capitulo', models.CharField(max_length=100, verbose_name='Capitulo')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
            ],
        ),
    ]
